# Generated by Django 3.1.2 on 2023-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230710_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionTalleres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtalleres', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=70)),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
