# Generated by Django 3.1.2 on 2023-06-25 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_suscripcion_tiposuscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_carrito',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='item_carrito',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='item_carrito',
            name='precio',
        ),
        migrations.AddField(
            model_name='item_carrito',
            name='items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_carrito',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='item_carrito',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
