# Generated by Django 3.1.2 on 2023-06-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230625_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_carrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
