# Generated by Django 3.1.2 on 2023-06-26 01:42

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230625_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompra',
            name='id',
        ),
        migrations.AddField(
            model_name='historialcompra',
            name='codigo',
            field=models.CharField(default=core.models.generar_codigo, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='historialcompra',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
